CREATE DATABASE IF NOT EXISTS tutordb;

CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `tutordb`.* TO 'root'@'%';
FLUSH PRIVILEGES;

use tutordb;
DROP TABLE IF EXISTS INTERNSHIP;
DROP TABLE IF EXISTS INTERN;
DROP TABLE IF EXISTS TUTOR;
DROP TABLE IF EXISTS COMPANY;


CREATE TABLE INTERN(
	ID INT NOT NULL AUTO_INCREMENT,
	LASTNAME VARCHAR(25),
	FIRSTNAME VARCHAR(25),
    PHONE VARCHAR(10),
	ADDRESS VARCHAR(150),
	POSTALCODE VARCHAR(15),
	CITY VARCHAR(25),
	EMAIL VARCHAR(25),
    PRIMARY KEY (ID)
);

INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
('Bond','James','0123456789','2 avenue 007','92700','Colombes','jbond@gmail.com');
INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
('Jones','Indiana','0145362787','10 rue des Aventuriers','92270','Bois-colombes','ijones@gmail.com');
INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
('Bourne','Jason','0187665987','65 rue Agent Secret Perdu','92700','Colombes','jbourne@yahoo.fr');
INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
('Stark','Arya','0187611987','6 rue Sans-Nom','75016','Paris','astark@nord.com');
INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
('Lanister','Cersei','0187384987','5 bvd des Reines','21000','Dijon','clanister@mail.co.uk');
INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
    ('Dupres','Louis','0187384987','5 bvd des Capucines','75013','Paris','louis@mail.com');
INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
    ('Laporte','Aymeric','0187384999','15 rue de la Paix','13012','Marseille','aLaporte@mail.co.es');
INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
    ('Lanister','Cersei','0187384987','5 bvd des Reines','21000','Dijon','clanister@mail.co.uk');
INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
    ('Kamara','Boubacar','0789898989','10 avenue de L or','35012','Rennes','b.kam@mail.fr');
INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
    ('Zidane','Zinedine','0187384987','55 bvd des Mirailles','21000','Lyon','zinedine.zidane@mail.com');
INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
    ('Grande','Lila','0187384987','5 bvd des Reines','21000','Dijon','lila.grande@mail.co.uk');
INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
    ('Stark','Sansa','0187384987','11 rue de Pythagore','75012','Paris','s-stark@mail.co.uk');
INSERT INTO INTERN(LASTNAME,FIRSTNAME,PHONE,ADDRESS,POSTALCODE,CITY,EMAIL) VALUES
    ('Queiros','Joachim','0678754531','87 avenue des Pirates','90865','Besancon','a-j@mail.co.fr');


CREATE TABLE TUTOR(
        ID INT NOT NULL AUTO_INCREMENT,
        FIRSTNAME VARCHAR(25),
        LASTNAME VARCHAR(25),
        EMAIL VARCHAR(25),
        PASSWORD VARCHAR(25),
        PRIMARY KEY (ID)
);

INSERT INTO TUTOR(FIRSTNAME, LASTNAME, EMAIL, PASSWORD) VALUES
('swan', 'bilek','swan@email.com', 'password123');
INSERT INTO TUTOR(FIRSTNAME, LASTNAME, EMAIL, PASSWORD) VALUES
    ('Steve', 'Jobs','ste.jobs@email.com', 'password123');


CREATE TABLE COMPANY(
                        ID INT NOT NULL AUTO_INCREMENT,
                        NAME VARCHAR(25),
                        ADDRESS VARCHAR(150),
                        POSTALCODE VARCHAR(25),
                        CITY VARCHAR(25),
                        PRIMARY KEY (ID)
);

INSERT INTO COMPANY(NAME, ADDRESS, POSTALCODE, CITY) VALUES
('SOCIETE GENERAL', '45 BOULEVARD JOURDAN', '75014', 'Paris');
INSERT INTO COMPANY(NAME, ADDRESS, POSTALCODE, CITY) VALUES
    ('THALES', '15 RUE DE LA PAIX', '75014', 'Paris');
INSERT INTO COMPANY(NAME, ADDRESS, POSTALCODE, CITY) VALUES
    ('FOOT LOCKER', '1 AVENUE PROPRE', '75014', 'Paris');
INSERT INTO COMPANY(NAME, ADDRESS, POSTALCODE, CITY) VALUES
    ('ZARA', '10 RUE PERNIER', '75013', 'Paris');
INSERT INTO COMPANY(NAME, ADDRESS, POSTALCODE, CITY) VALUES
    ('BNP', '10 RUE PERNIER', '75013', 'Paris');
INSERT INTO COMPANY(NAME, ADDRESS, POSTALCODE, CITY) VALUES
    ('UBISOFT', '10 RUE MERCIER', '75013', 'Paris');


CREATE TABLE INTERNSHIP(
        ID INT NOT NULL AUTO_INCREMENT,
		ID_INTERN INT NOT NULL,
		ID_TUTOR INT NOT NULL,
        ID_COMPANY INT NOT NULL,
		NOTE_TECH VARCHAR(10),
        NOTE_COM VARCHAR(10),
        MISSION VARCHAR(300),
        CDC BOOLEAN,
        VISIT_SHEET BOOLEAN,
        EVAL_SHEET BOOLEAN,
        WEB_SURVEY BOOLEAN,
        REPORT BOOLEAN,
        DEFENSE BOOLEAN,
        STARTED_DATE DATE,
        ENDED_DATE DATE,
        CONSTRAINT FK_COMPANY
        FOREIGN KEY (ID_COMPANY) REFERENCES COMPANY(ID) ON DELETE CASCADE,
		CONSTRAINT FK_INTERN
        FOREIGN KEY (ID_INTERN) REFERENCES INTERN(ID) ON DELETE CASCADE,
        CONSTRAINT FK_TUTOR
        FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID) ON DELETE CASCADE,
		PRIMARY KEY (ID)
);

INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
(1, 3,1,'x','x','Developpeur web', true, false, false, false, false, false, '2023-04-01', '2023-09-01');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (2, 1,1,'x','x','Assistant robotique', false, false, false, false, false, false, '2023-04-01', '2023-10-01');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (3, 2,1,'x','x','Vendeur polyvalent', false, true, false, false, false, false, '2023-04-01', '2023-09-01');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (4, 4,1,'x','x','Caissier', false, false, false, false, false, false, '2023-04-01', '2023-09-01');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (5, 9,1,'x','x','Analyste financier', true, false, false, false, false, false, '2023-04-01', '2023-09-01');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (6, 12,1,'x','x','Responsable RH', false, false, true, false, false, false, '2023-01-01', '2023-09-01');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (2, 8,1,'x','x','Product manager', false, true, false, false, false, false, '2023-02-01', '2023-10-01');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (5, 11,1,'x','x','Commercial', false, true, false, false, false, false, '2022-04-01', '2023-09-01');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (3,6, 1,'x','x','Product owner', false, false, false, false, false, false, '2022-04-01', '2024-01-11');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (3, 5,1,'x','x','UI designer', false, true, false, false, false, false, '2022-04-01', '2023-09-01');

INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (1, 4,2,'x','x','Development', false, false, true, false, false, false, '2023-04-01', '2023-09-01');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (4, 3,2,'x','x','Caissier', true, false, true, false, false, false, '2023-04-01', '2024-01-01');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (3, 1,2,'x','x','Vendeur polyvalent', false, false, false, false, false, false, '2023-04-01', '2023-10-30');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (6, 10,2,'x','x','Developpeur', false, false, false, false, false, false, '2023-04-01', '2023-10-30');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (1, 12,2,'x','x','Data analyst', true, true, false, false, false, false, '2023-04-01', '2023-10-30');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (3, 9,2,'x','x','Vendeur polyvalent', false, false, false, false, false, false, '2023-04-01', '2023-10-30');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (5, 7,2,'x','x','Product owner', false, false, true, true, false, false, '2023-04-01', '2023-10-30');
INSERT INTO INTERNSHIP(ID_COMPANY,ID_INTERN, ID_TUTOR,NOTE_TECH, NOTE_COM, MISSION, CDC, VISIT_SHEET, EVAL_SHEET, WEB_SURVEY, REPORT, DEFENSE, STARTED_DATE, ENDED_DATE) VALUES
    (3, 11,2,'x','x','Commercial', false, false, false, false, false, false, '2023-04-01', '2023-10-30');


